# Generated by Django 3.1.4 on 2020-12-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_list', '0002_list_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
