# Generated by Django 3.1.4 on 2020-12-20 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memo_list', '0003_auto_20201220_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
